spring.application.name=api

# MongoDB
spring.mongodb.uri=${DATABASE_URI}?retryWrites=true&w=majority

# JWT
jwt.secret=${JWT_SECRET_KEY}

# Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.operationsSorter=method

